### ISSUE TITLE
Append doesn't work on datetimes

### ISSUE THREAD

**Issue by Frankkkkk** [ranaroussi/pystore#9] opened 2019-01-13 20:12 UTC
Hi,
First of all, thank you for this project ;-)

I've got a little problem with the append function: it doesn't do anything with the indexes are datetimes:
```python3
pystore.set_path('/dev/shm/test/pystore')
store = pystore.store('mydatastore')
collection = store.collection('collection')


item = 'test'

it1 = pd.DataFrame({'data': {datetime.datetime(2019, 1, 1): random.random()}})
collection.write(item, it1, overwrite=True)

it2 = pd.DataFrame({'data': {datetime.datetime(2019, 1, 2): random.random()}})
collection.append(item, it2)


it = collection.item(item)
df = it.to_pandas()
print(df)
```
yields:
```
                data
index               
2019-01-01  0.450675
```

However, if I use a timestamp instead of a datetime (`datetime.datetime(xxx).timestamp()`), it works:
```
                         data
index                        
2018-12-31 23:00:00  0.385200
2019-01-01 23:00:00  0.639432
```

Thanks

**Comment by ranaroussi** [comment] 2019-03-23 09:35
Can't reproduce. Closing this for now...

**Closed by ranaroussi** 2019-03-23 09:35 UTC
